
POST http://localhost:3000/prodotti/donna/vestaglie
Content-Type: application/json

{  "pic_src":"./public/images/vestaglia.jpg",
    "name":"v4",
    "category":"vestaglie",
    "gender": "donna",
    "brand":"Andra",
    "material":"Raso",
    "color":"Blu",
    "size":["S","M","L","XL","XXL"],
    "price": 45.00,
    "description": "Pigiama di raso di Andra - blu"
}

###
GET http://localhost:3000/prodotti/donna/vestaglie
Content-Type: application/json


###
GET http://localhost:3000/prodotti/donna/vestaglie/613dce950d2b2b6ab7f0b2e9
Content-Type: application/json

###
DELETE http://localhost:3000/prodotti/
Content-Type: application/json

###
DELETE http://localhost:3000/prodotti/donna/vestaglie/613dcee80d2b2b6ab7f0b2ed
Content-Type: application/json