
POST http://localhost:3000/prodotti/donna/vestaglie
Content-Type: application/json

{  "pic_src":"./public/images/vestaglia.jpg",
    "name":"v4",
    "category":"vestaglie",
    "gender": "donna",
    "brand":"Andra",
    "material":"Raso",
    "color":"Blu",
    "size":["S","M","L","XL","XXL"],
    "price": 45.00,
    "description": "Pigiama di raso di Andra - blu"
}

###
DELETE http://localhost:3000/prodotti/donna/vestaglie
Content-Type: application/json

{  
    ["cia"] "./public/images/vestaglia."
}