###
POST http://localhost:3000/purchase/confirm
Content-Type: application/json

{
    "email":"see@m.com",
    "items":[
        { product_name: {
    type: String,
  },
  category: {
    type: String,
  },
  gender: { type: String },
  brand: { type: String },
  material: { type: String },
  color: { type: String },
  size: { type: String },
  price: { type: Number },
            "_id":"60718ed44df22143082be549",
            "stock":2,
            "price":12
        }
       
    ]
}